import React, { useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { KeyboardAvoidingView } from 'react-native-keyboard-controller';
import { Feather } from '@expo/vector-icons';
import { useColors } from '@/hooks/useColors';
import { BrandRule } from '@/components/BrandDecor';
import { Header, Screen } from '@/components/Screen';
import { useOperations } from '@/context/OperationsContext';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useDemo } from '@/context/DemoContext';

export default function ChatScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { messages, addMessage } = useOperations(); const { isDemoMode, isReadOnly, profile } = useDemo(); const [draft, setDraft] = useState('');
  const send = () => { if (isReadOnly) return; if (!draft.trim()) return; addMessage(draft.trim()); setDraft(''); };
   return <KeyboardAvoidingView behavior="padding" style={{ flex: 1, backgroundColor: colors.background }} keyboardVerticalOffset={0}><Screen><Header eyebrow={isDemoMode ? `${profile.store?.name ?? 'All stores'} team` : 'Pitt Street team'} title="Team chat" action="more-horizontal" /><View style={styles.editorialKicker}><Text style={[styles.kickerText, { color: colors.primary }]}>04 / TEAM SIGNAL</Text><BrandRule color={colors.accent} /></View><View style={[styles.info, { backgroundColor: colors.secondary }]}><Feather name={isReadOnly ? 'eye' : 'lock'} color={colors.secondaryForeground} size={15} /><Text style={[styles.infoText, { color: colors.secondaryForeground }]}>{isReadOnly ? 'Read-only viewer · team messages are visible' : isDemoMode ? 'Preview chat · messages stay on this device' : 'Only your store team can see this chat'}</Text></View><FlatList data={messages} keyExtractor={(item) => item.id} style={styles.list} contentContainerStyle={styles.listContent} renderItem={({ item }) => <View style={[styles.messageLine, item.mine && styles.mine]}><View style={[styles.avatar, { backgroundColor: item.mine ? colors.primary : colors.accent }]}><Text style={[styles.avatarText, { color: item.mine ? '#fff' : colors.accentForeground }]}>{item.author.split(' ').map((n) => n[0]).join('').slice(0, 2)}</Text></View><View style={[styles.bubble, { backgroundColor: item.mine ? colors.primary : colors.card, borderColor: colors.border }]}><Text style={[styles.author, { color: item.mine ? '#FFDAD1' : colors.primary }]}>{item.author}</Text><Text style={[styles.message, { color: item.mine ? '#fff' : colors.foreground }]}>{item.text}</Text><Text style={[styles.time, { color: item.mine ? '#FFDAD1' : colors.mutedForeground }]}>{item.time}</Text></View></View>} scrollEnabled={messages.length > 0} showsVerticalScrollIndicator={false} /><View style={[styles.composer, { borderTopColor: colors.border, paddingBottom: Math.max(insets.bottom, 10) }]}><Pressable disabled={isReadOnly} style={[styles.attach, { backgroundColor: colors.secondary, opacity: isReadOnly ? .5 : 1 }]}><Feather name="paperclip" color={colors.foreground} size={18} /></Pressable><TextInput testID="chat-input" value={draft} onChangeText={setDraft} onSubmitEditing={send} editable={!isReadOnly} returnKeyType="send" placeholder={isReadOnly ? 'Viewer profile is read-only' : 'Message your team...'} placeholderTextColor={colors.mutedForeground} style={[styles.textInput, { color: colors.foreground, backgroundColor: colors.card, borderColor: colors.border, opacity: isReadOnly ? .6 : 1 }]} /><Pressable testID="send-message" onPress={send} disabled={isReadOnly} style={({ pressed }) => [styles.send, { backgroundColor: colors.primary, opacity: pressed || isReadOnly ? .5 : 1 }]}><Feather name="arrow-up" color="#fff" size={19} /></Pressable></View></Screen></KeyboardAvoidingView>;
}
 const styles = StyleSheet.create({ editorialKicker: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 10 }, kickerText: { fontFamily: 'SpaceMono_700Bold', fontSize: 9, letterSpacing: 1 }, info: { flexDirection: 'row', alignItems: 'center', gap: 7, padding: 11, borderRadius: 12, marginBottom: 12 }, infoText: { fontFamily: 'Inter_500Medium', fontSize: 11 }, list: { flex: 1 }, listContent: { paddingBottom: 12 }, messageLine: { flexDirection: 'row', gap: 9, marginVertical: 6, maxWidth: '91%' }, mine: { alignSelf: 'flex-end', flexDirection: 'row-reverse' }, avatar: { width: 31, height: 31, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontFamily: 'Inter_700Bold', fontSize: 10 }, bubble: { borderRadius: 16, borderWidth: 1, padding: 11, flexShrink: 1 }, author: { fontFamily: 'Inter_700Bold', fontSize: 11, marginBottom: 4 }, message: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19 }, time: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 6, textAlign: 'right' }, composer: { flexDirection: 'row', gap: 8, alignItems: 'center', borderTopWidth: 1, paddingTop: 10 }, attach: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, textInput: { flex: 1, minHeight: 42, borderRadius: 14, borderWidth: 1, paddingHorizontal: 13, fontFamily: 'Inter_400Regular', fontSize: 13 }, send: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' } });