// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ausease/OperationsRunway.tsx": () => import("../components/mockups/ausease/OperationsRunway.tsx"),
  "./components/mockups/ausease/OperationsRunwayLime.tsx": () => import("../components/mockups/ausease/OperationsRunwayLime.tsx")
};
